/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricketproj2021;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class matchhistory extends javax.swing.JFrame {

    /**
     
     */
    public matchhistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        sa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sb = new javax.swing.JTextField();
        ta = new javax.swing.JTextField();
        txtfinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtw2 = new javax.swing.JTextField();
        txtw1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        team1inn1 = new javax.swing.JTextField();
        team1inn2 = new javax.swing.JTextField();
        team2inn1 = new javax.swing.JTextField();
        team2inn2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbm = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MATCH DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER MATCH DAY NUMBER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TEAM 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 78, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("TEAM 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 128, -1, -1));

        tb.setEditable(false);
        jPanel1.add(tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 128, 67, -1));

        sa.setEditable(false);
        jPanel1.add(sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 78, 67, 24));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SCORE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        sb.setEditable(false);
        sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbActionPerformed(evt);
            }
        });
        jPanel1.add(sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 128, 67, -1));

        ta.setEditable(false);
        jPanel1.add(ta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 78, 67, 24));

        txtfinal.setEditable(false);
        txtfinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 194, 548, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("WICKETS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        txtw2.setEditable(false);
        jPanel1.add(txtw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 128, 60, -1));

        txtw1.setEditable(false);
        jPanel1.add(txtw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ist INNING");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("IInd INNING");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        team1inn1.setEditable(false);
        jPanel1.add(team1inn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 80, 94, -1));

        team1inn2.setEditable(false);
        jPanel1.add(team1inn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 80, 90, -1));

        team2inn1.setEditable(false);
        jPanel1.add(team2inn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 128, 94, -1));

        team2inn2.setEditable(false);
        jPanel1.add(team2inn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 128, 90, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 43, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 600, 240));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        cbm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        getContentPane().add(cbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 130, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cricketproj2021/match history pic.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 670, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
mainframe mf4=new mainframe();
mf4.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
JOptionPane.showMessageDialog(null,"PLEASE SELECT A MATCHDAY NUMBER");
        try{
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cricket","root","1192002");
            Statement stmt=con.createStatement();
            String str="Select mno from matchday;";
            ResultSet rs=stmt.executeQuery(str);
            while(rs.next())
            {
                    int mn=rs.getInt("mno");
                    String ans=Integer.toString(mn);
                    cbm.addItem(ans);
            }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);    
}
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cricket","root","1192002");
            Statement stmt=con.createStatement();
            int sm=Integer.parseInt((String)cbm.getSelectedItem());
            
            String std="Select * from matchday where mno="+sm+";";
            ResultSet rsd=stmt.executeQuery(std);
            if(rsd.next());
            {
                
                String ta1=rsd.getString("t1");
                String tb2=rsd.getString("t2");
                int tas1=rsd.getInt("score1");
                int tbs2=rsd.getInt("score2");
                int wmt1=rsd.getInt("wicket1");
                int wmt2=rsd.getInt("wicket2");
                String t1in2=rsd.getString("t1inn2");
                String t2in2=rsd.getString("t2inn2");
                ta.setText(""+ta1);
                tb.setText(""+tb2);
                sa.setText(""+tas1);
                sb.setText(""+tbs2);
                txtw1.setText(""+wmt1);
                txtw2.setText(""+wmt2);
                team1inn2.setText(""+t1in2);
                team2inn2.setText(""+t2in2);
                team1inn1.setText(""+t2in2);
                team2inn1.setText(""+t1in2);
                
                if(t1in2.equals("BATTING"))
                {
                    if(tas1>tbs2)
                    {
                        txtfinal.setText(""+ta1+" won by "+(10-wmt1)+" wickets");
                    }else{
                        txtfinal.setText(""+tb2+" won by "+(tbs2-tas1)+" runs");
                         }
                }else if(t1in2.equals("BOWLING"))
                {
                    if(tas1>tbs2)
                    {
                        txtfinal.setText(""+ta1+" won by "+(tas1-tbs2)+" runs");                        
                    }else{
                        txtfinal.setText(""+tb2+" won by "+(10-wmt2)+" wickets");
                    }
                }
                
                
               
            }
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"PLEASE SELECT A MATCHDAY NUMBER");
}   
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

ta.setText(" ");
tb.setText(" ");
sa.setText(" ");
sb.setText(" ");
txtw1.setText(" ");
txtw2.setText(" ");
txtfinal.setText(" ");
team1inn1.setText(" ");
team1inn2.setText(" ");
team2inn2.setText(" ");
team2inn1.setText(" ");


cbm.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matchhistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matchhistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matchhistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matchhistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matchhistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sa;
    private javax.swing.JTextField sb;
    private javax.swing.JTextField ta;
    private javax.swing.JTextField tb;
    private javax.swing.JTextField team1inn1;
    private javax.swing.JTextField team1inn2;
    private javax.swing.JTextField team2inn1;
    private javax.swing.JTextField team2inn2;
    private javax.swing.JTextField txtfinal;
    private javax.swing.JTextField txtw1;
    private javax.swing.JTextField txtw2;
    // End of variables declaration//GEN-END:variables
}
