/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricketproj2021;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class pointstable extends javax.swing.JFrame {

    /**
     * Creates new form pointstable
     */
    public pointstable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teams1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tm1 = new javax.swing.JTextField();
        tm2 = new javax.swing.JTextField();
        tm4 = new javax.swing.JTextField();
        tm5 = new javax.swing.JTextField();
        tm3 = new javax.swing.JTextField();
        w1 = new javax.swing.JTextField();
        w3 = new javax.swing.JTextField();
        w2 = new javax.swing.JTextField();
        w4 = new javax.swing.JTextField();
        w5 = new javax.swing.JTextField();
        l2 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        l3 = new javax.swing.JTextField();
        l4 = new javax.swing.JTextField();
        l5 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        pd1 = new javax.swing.JTextField();
        pd3 = new javax.swing.JTextField();
        pd2 = new javax.swing.JTextField();
        pd4 = new javax.swing.JTextField();
        pd5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        teams1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---select team---" }));
        teams1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teams1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teams1FocusLost(evt);
            }
        });
        teams1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teams1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POINTS TABLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 32, -1, 54));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TEAMS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 114, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WINS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 114, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOST");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 114, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("POINTS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 104, 665, 30));

        tm1.setEditable(false);
        getContentPane().add(tm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 161, 80, -1));

        tm2.setEditable(false);
        getContentPane().add(tm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 208, 80, -1));

        tm4.setEditable(false);
        getContentPane().add(tm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 311, 80, -1));

        tm5.setEditable(false);
        getContentPane().add(tm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 362, 80, -1));

        tm3.setEditable(false);
        getContentPane().add(tm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 263, 80, -1));

        w1.setEditable(false);
        w1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(w1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 161, 37, -1));

        w3.setEditable(false);
        w3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(w3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 263, 37, -1));

        w2.setEditable(false);
        w2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(w2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 208, 37, -1));

        w4.setEditable(false);
        w4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(w4, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 311, 37, -1));

        w5.setEditable(false);
        w5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(w5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 362, 37, -1));

        l2.setEditable(false);
        l2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 208, 36, -1));

        l1.setEditable(false);
        l1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 161, 36, -1));

        l3.setEditable(false);
        l3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 263, 36, -1));

        l4.setEditable(false);
        l4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 311, 36, -1));

        l5.setEditable(false);
        l5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 362, 36, -1));

        p2.setEditable(false);
        p2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 208, 37, -1));

        p3.setEditable(false);
        p3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 263, 37, -1));

        p1.setEditable(false);
        p1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 161, 37, -1));

        p4.setEditable(false);
        p4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 311, 37, -1));

        p5.setEditable(false);
        p5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 362, 37, -1));

        pd1.setEditable(false);
        pd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd1ActionPerformed(evt);
            }
        });
        getContentPane().add(pd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 161, 37, -1));

        pd3.setEditable(false);
        pd3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 263, 37, -1));

        pd2.setEditable(false);
        pd2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 208, 37, -1));

        pd4.setEditable(false);
        pd4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 311, 37, -1));

        pd5.setEditable(false);
        pd5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 362, 37, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLAYED");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 114, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 160, 30, -1));

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 208, 30, -1));

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 263, 30, -1));

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 311, 30, -1));

        jTextField5.setEditable(false);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("5");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 362, 30, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("POS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 114, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cricketproj2021/points table.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
mainframe m9=new mainframe();
m9.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

       try{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cricket","root","1192002");
            Statement stmt=con.createStatement();
            String del="Delete from pointstable";
            stmt.executeUpdate(del);
             String team="select t_name from teamdetails";
             ResultSet rs=stmt.executeQuery(team);
             String tnm[]=new String[5];
             int temp=0;
             while(rs.next())
             {
                 
                     String s1=rs.getString("t_name");
                     tnm[temp]=s1;
                     temp++;
                     
             }  
             String n1=tnm[0];
             String n2=tnm[1];
             String n3=tnm[2];
             String n4=tnm[3];
             String n5=tnm[4];
             
             
            
             
             int a1=0,a2=0,a3=0,a4=0,a5=0,a6=0,a7=0,a8=0,a9=0,a10=0;
              String str1="select count(teamwin) from win where teamwin= '"+n1+"';";            
              ResultSet rs1=stmt.executeQuery(str1);
              if(rs1.next())
              {
                  a1=rs1.getInt("count(teamwin)");
                      
              }           
              String str2="select count(teamloss) from loss where teamloss= '"+n1+"';";
              ResultSet rs2=stmt.executeQuery(str2);
              if(rs2.next())
              {
                  a2=rs2.getInt("count(teamloss)");
                        
              }
              String str3="select count(teamwin) from win where teamwin= '"+n2+"';";            
              ResultSet rs3=stmt.executeQuery(str3);
              if(rs3.next())
              {
                  a3=rs3.getInt("count(teamwin)");
                      
              }           
              String str4="select count(teamloss) from loss where teamloss= '"+n2+"';";
              ResultSet rs4=stmt.executeQuery(str4);
              if(rs4.next())
              {
                  a4=rs4.getInt("count(teamloss)");
                       
              }
               String str5="select count(teamwin) from win where teamwin= '"+n3+"';";            
              ResultSet rs5=stmt.executeQuery(str5);
              if(rs5.next())
              {
                  a5=rs5.getInt("count(teamwin)");
                      
              }           
              String str6="select count(teamloss) from loss where teamloss= '"+n3+"';";
              ResultSet rs6=stmt.executeQuery(str6);
              if(rs6.next())
              {
                  a6=rs6.getInt("count(teamloss)");
                       
              }
              String str7="select count(teamwin) from win where teamwin= '"+n4+"';";            
              ResultSet rs7=stmt.executeQuery(str7);
              if(rs7.next())
              {
                  a7=rs7.getInt("count(teamwin)");
                      
              }           
              String str8="select count(teamloss) from loss where teamloss= '"+n4+"';";
              ResultSet rs8=stmt.executeQuery(str8);
              if(rs8.next())
              {
                  a8=rs8.getInt("count(teamloss)");
                       
              }String str9="select count(teamwin) from win where teamwin= '"+n5+"';";            
              ResultSet rs9=stmt.executeQuery(str9);
              if(rs9.next())
              {
                  a9=rs9.getInt("count(teamwin)");
                      
              }           
              String str10="select count(teamloss) from loss where teamloss= '"+n5+"';";
              ResultSet rs10=stmt.executeQuery(str10);
              if(rs10.next())
              {
                  a10=rs10.getInt("count(teamloss)");
                       
              }
              int point1=a1*3+a2*0;
              int point2=a3*3+a4*0;
              int point3=a5*3+a6*0;
              int point4=a7*3+a8*0;
              int point5=a9*3+a10*0;
              
              String tp1="Insert into pointstable values('"+n1+"',"+a1+","+a2+","+point1+");";
              stmt.executeUpdate(tp1);
              String tp2="Insert into pointstable values('"+n2+"',"+a3+","+a4+","+point2+");";
              stmt.executeUpdate(tp2);
              String tp3="Insert into pointstable values('"+n3+"',"+a5+","+a6+","+point3+");";
              stmt.executeUpdate(tp3);
              String tp4="Insert into pointstable values('"+n4+"',"+a7+","+a8+","+point4+");";
              stmt.executeUpdate(tp4);
              String tp5="Insert into pointstable values('"+n5+"',"+a9+","+a10+","+point5+");";
              stmt.executeUpdate(tp5);
              int wins[]=new int[5];
              int lost[]=new int[5];
              int points[]=new int[5];
              String teamsn[]=new String[5];
              
              String finalp="select * from pointstable order by point desc;";
               ResultSet rf=stmt.executeQuery(finalp);
               int count=0;
               while(rf.next())
               {
                   String team1=rf.getString("teampoint");
                   int win1=rf.getInt("wins");
                   int loss1=rf.getInt("lost");
                   int pt1=rf.getInt("point");
                   teamsn[count]=team1;
                   wins[count]=win1;
                   lost[count]=loss1;
                   points[count]=pt1;
                   count++;
                      
               }
               tm1.setText(""+teamsn[0]);
               w1.setText(""+wins[0]);
               l1.setText(""+lost[0]);
               p1.setText(""+points[0]);
               tm2.setText(""+teamsn[1]);
               w2.setText(""+wins[1]);
               l2.setText(""+lost[1]);
               p2.setText(""+points[1]);
               tm3.setText(""+teamsn[2]);
               w3.setText(""+wins[2]);
               l3.setText(""+lost[2]);
               p3.setText(""+points[2]);
               tm4.setText(""+teamsn[3]);
               w4.setText(""+wins[3]);
               l4.setText(""+lost[3]);
               p4.setText(""+points[3]);
               tm5.setText(""+teamsn[4]);
               w5.setText(""+wins[4]);
               l5.setText(""+lost[4]);
               p5.setText(""+points[4]);
               int x1=Integer.parseInt(w1.getText());
               int x2=Integer.parseInt(l1.getText());
               int x3=Integer.parseInt(w2.getText());
               int x4=Integer.parseInt(l2.getText());
               int x5=Integer.parseInt(w3.getText());
               int x6=Integer.parseInt(l3.getText());
               int x7=Integer.parseInt(w4.getText());
               int x8=Integer.parseInt(l4.getText());
               int x9=Integer.parseInt(w5.getText());
               int x10=Integer.parseInt(l5.getText());
               pd1.setText(""+(x1+x2));
               pd2.setText(""+(x3+x4));
               pd3.setText(""+(x5+x6));
               pd4.setText(""+(x7+x8));
               pd5.setText(""+(x9+x10));
               
               
               
               
               
              
             
             
             
            
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void teams1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teams1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_teams1FocusGained

    private void teams1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teams1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_teams1FocusLost

    private void teams1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teams1ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_teams1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pointstable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pointstable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pointstable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pointstable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pointstable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField l1;
    private javax.swing.JTextField l2;
    private javax.swing.JTextField l3;
    private javax.swing.JTextField l4;
    private javax.swing.JTextField l5;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField pd1;
    private javax.swing.JTextField pd2;
    private javax.swing.JTextField pd3;
    private javax.swing.JTextField pd4;
    private javax.swing.JTextField pd5;
    private javax.swing.JComboBox<String> teams1;
    private javax.swing.JTextField tm1;
    private javax.swing.JTextField tm2;
    private javax.swing.JTextField tm3;
    private javax.swing.JTextField tm4;
    private javax.swing.JTextField tm5;
    private javax.swing.JTextField w1;
    private javax.swing.JTextField w2;
    private javax.swing.JTextField w3;
    private javax.swing.JTextField w4;
    private javax.swing.JTextField w5;
    // End of variables declaration//GEN-END:variables
}
