/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricketproj2021;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class scoreboard extends javax.swing.JFrame {

    /**
     * Creates new form scoreboard
     */
    public scoreboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        t1 = new javax.swing.JComboBox<>();
        t2 = new javax.swing.JComboBox<>();
        st1 = new javax.swing.JTextField();
        st2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        matchdayno = new javax.swing.JTextField();
        finish = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        bat1 = new javax.swing.JRadioButton();
        bowl1 = new javax.swing.JRadioButton();
        bat2 = new javax.swing.JRadioButton();
        bowl2 = new javax.swing.JRadioButton();
        wicket1 = new javax.swing.JTextField();
        wicket2 = new javax.swing.JTextField();
        w1minus = new javax.swing.JButton();
        w2plus = new javax.swing.JButton();
        w1plus = new javax.swing.JButton();
        w2minus = new javax.swing.JButton();
        inn11 = new javax.swing.JRadioButton();
        inn12 = new javax.swing.JRadioButton();
        inn21 = new javax.swing.JRadioButton();
        inn22 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b22 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        cbutton = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---select team---" }));
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t1FocusLost(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 132, 120, -1));

        t2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---select team---" }));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 129, -1));

        st1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        st1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        st1.setText("0");
        getContentPane().add(st1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 289, 120, 61));

        st2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        st2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        st2.setText("0");
        st2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st2ActionPerformed(evt);
            }
        });
        getContentPane().add(st2, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 289, 129, 61));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEAM 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 93, -1, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TEAM 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 68, 41));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MATCHDAY NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 165, 25));

        matchdayno.setEditable(false);
        matchdayno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchdaynoActionPerformed(evt);
            }
        });
        getContentPane().add(matchdayno, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 42, 36));

        finish.setText("FINISH");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        getContentPane().add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        b16.setText("6");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        getContentPane().add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 385, -1, -1));

        b14.setText("4");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 385, -1, -1));

        b13.setText("3");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 385, -1, -1));

        b12.setText("2");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 385, -1, -1));

        b11.setText("1");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 385, -1, -1));

        buttonGroup1.add(bat1);
        bat1.setForeground(new java.awt.Color(255, 255, 255));
        bat1.setText("BATTING");
        bat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bat1ActionPerformed(evt);
            }
        });
        getContentPane().add(bat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 170, -1, -1));

        buttonGroup1.add(bowl1);
        bowl1.setForeground(new java.awt.Color(255, 255, 255));
        bowl1.setText("BOWLING");
        bowl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowl1ActionPerformed(evt);
            }
        });
        getContentPane().add(bowl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 193, -1, -1));

        buttonGroup3.add(bat2);
        bat2.setForeground(new java.awt.Color(255, 255, 255));
        bat2.setText("BATTING");
        bat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bat2ActionPerformed(evt);
            }
        });
        getContentPane().add(bat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 170, -1, -1));

        buttonGroup3.add(bowl2);
        bowl2.setForeground(new java.awt.Color(255, 255, 255));
        bowl2.setText("BOWLING");
        bowl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowl2ActionPerformed(evt);
            }
        });
        getContentPane().add(bowl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 196, -1, -1));

        wicket1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        wicket1.setText("0");
        getContentPane().add(wicket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 304, 49, 34));

        wicket2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        wicket2.setText("0");
        getContentPane().add(wicket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 304, 49, 34));

        w1minus.setText("-");
        w1minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w1minusActionPerformed(evt);
            }
        });
        getContentPane().add(w1minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 344, 40, -1));

        w2plus.setText("+");
        w2plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w2plusActionPerformed(evt);
            }
        });
        getContentPane().add(w2plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 275, 40, -1));

        w1plus.setText("+");
        w1plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w1plusActionPerformed(evt);
            }
        });
        getContentPane().add(w1plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 275, 40, -1));

        w2minus.setText("-");
        w2minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w2minusActionPerformed(evt);
            }
        });
        getContentPane().add(w2minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 344, 40, -1));

        buttonGroup2.add(inn11);
        inn11.setForeground(new java.awt.Color(255, 255, 255));
        inn11.setText("Ist INNING");
        inn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inn11ActionPerformed(evt);
            }
        });
        getContentPane().add(inn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 170, 87, -1));

        buttonGroup2.add(inn12);
        inn12.setForeground(new java.awt.Color(255, 255, 255));
        inn12.setText("IInd INNING ");
        inn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inn12ActionPerformed(evt);
            }
        });
        getContentPane().add(inn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 196, -1, -1));

        buttonGroup4.add(inn21);
        inn21.setForeground(new java.awt.Color(255, 255, 255));
        inn21.setText("Ist INNING");
        inn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inn21ActionPerformed(evt);
            }
        });
        getContentPane().add(inn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 87, -1));

        buttonGroup4.add(inn22);
        inn22.setForeground(new java.awt.Color(255, 255, 255));
        inn22.setText("IInd INNING ");
        inn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inn22ActionPerformed(evt);
            }
        });
        getContentPane().add(inn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 196, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RUNS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 243, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WICKETS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 243, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RUNS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("WICKETS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 240, -1, -1));

        b22.setText("2");
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 385, -1, -1));

        b21.setText("1");
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        getContentPane().add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 385, -1, -1));

        b26.setText("6");
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });
        getContentPane().add(b26, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 385, -1, -1));

        b24.setText("4");
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        getContentPane().add(b24, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 385, -1, -1));

        b23.setText("3");
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        getContentPane().add(b23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 385, -1, -1));

        cbutton.setText("CONTINUE");
        cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(cbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        next.setText("NEXT INNING");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cricketproj2021/scoreboard.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 900, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
inn12.setVisible(false);
inn22.setVisible(false);
        st1.setEnabled(false);
st2.setEnabled(false);
wicket1.setEnabled(false);
wicket2.setEnabled(false);
finish.setEnabled(false);
b16.setEnabled(false);
b14.setEnabled(false);
b13.setEnabled(false);
b12.setEnabled(false);
b11.setEnabled(false);
b26.setEnabled(false);
b24.setEnabled(false);
b23.setEnabled(false);
b22.setEnabled(false);
b21.setEnabled(false);
w1plus.setEnabled(false);
w1minus.setEnabled(false);
w2plus.setEnabled(false);
w2minus.setEnabled(false);
bat1.setEnabled(false);
        bowl1.setEnabled(false);
        bat2.setEnabled(false);
        bowl2.setEnabled(false);
        inn11.setEnabled(false);
        inn12.setEnabled(false);
        inn21.setEnabled(false);
        inn22.setEnabled(false);
cbutton.setEnabled(false);
next.setEnabled(false);
inn11.setSelected(true);
inn21.setSelected(true);
        try{
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cricket","root","1192002");
            Statement stmt=con.createStatement();
            String team="select t_name from teamdetails";
             ResultSet rs=stmt.executeQuery(team);
             while(rs.next())
             {
                 
                     String s1=rs.getString("t_name");
                     t1.addItem(s1);
                     t2.addItem(s1);
                 }
             String mn="Select count(*) from matchday";
             ResultSet rs2=stmt.executeQuery(mn);
          if(rs2.next())
          {
               int mnt =rs2.getInt("count(*)");
               matchdayno.setText(""+(mnt+1));
          }
         
          
}
        
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
        int check=Integer.parseInt(matchdayno.getText());
        if(check>20)
        {
            matchdayno.setText("20");
            JOptionPane.showMessageDialog(null,"All matches has been played hence tournament ended");
             mainframe mf11 =new mainframe();
    mf11.setVisible(true);    
    this.dispose();
            
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
int res=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO FINISH THE MATCH?");
if(res==JOptionPane.YES_OPTION)
{
    int x1=Integer.parseInt(st1.getText());
    int x2=Integer.parseInt(st2.getText());
    int x3=Integer.parseInt(wicket1.getText());
    int x4=Integer.parseInt(wicket2.getText());
    if((x1>0 && x2>0) && ((x3>=0 && x3<=10) && (x4>=0 && x4<=10)))
    {
    try{
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cricket","root","1192002");
            Statement stmt=con.createStatement();
            if(bat1.isSelected()==true)
            {
                String strm="Insert into matchday values ("+matchdayno.getText()+",'"+ t1.getSelectedItem()+"','"+ t2.getSelectedItem()+"',"+st1.getText()+","+st2.getText()+","+wicket1.getText()+","+wicket2.getText()+",'"+bat1.getText()+"','"+bowl2.getText()+"');";
                stmt.executeUpdate(strm);                 
            }else if(bowl1.isSelected()==true)
            {
                String strm="Insert into matchday values ("+matchdayno.getText()+",'"+ t1.getSelectedItem()+"','"+ t2.getSelectedItem()+"',"+st1.getText()+","+st2.getText()+","+wicket1.getText()+","+wicket2.getText()+",'"+bowl1.getText()+"','"+bat2.getText()+"');";                
                stmt.executeUpdate(strm); 
            }
            
            int tp1=Integer.parseInt(st1.getText());
            int tp2=Integer.parseInt(st2.getText());
                        
            if(tp1>tp2)
            {
                String stm1="Insert into win values('"+(String)t1.getSelectedItem()+"');";     
                String stm2="Insert into loss values('"+(String)t2.getSelectedItem()+"');";  
                stmt.executeUpdate(stm1);
                stmt.executeUpdate(stm2);
                
                JOptionPane.showMessageDialog(null, "match ended");
                 mainframe mf=new mainframe();
        mf.setVisible(true);
        this.dispose();
            }else if(tp1==tp2)
            {
                JOptionPane.showMessageDialog(null,"TIE IS NOT POSSIBLE.");
                
            }else 
            {
                String st3="Insert into win values('"+(String)t2.getSelectedItem()+"');";     
               String st4="Insert into loss values('"+(String)t1.getSelectedItem()+"');";
               stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                JOptionPane.showMessageDialog(null, "match ended");
                 mainframe mf=new mainframe();
        mf.setVisible(true);
        this.dispose();
                
            }             
        }
         
    catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }else
            {
                    JOptionPane.showMessageDialog(null,"ENTER THE SCORES CORRECTLY");
            }
}// TODO add your handling code here:
    }//GEN-LAST:event_finishActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
String tn1=(String) t1.getSelectedItem();
String tn2=(String) t2.getSelectedItem();
if(tn1==tn2)
{
    JOptionPane.showMessageDialog(null,"PLEASE SELECT TWO DIFFERENT TEAMS");
    
}else if(tn1=="---select team---" || tn2=="---select team---")
{
    JOptionPane.showMessageDialog(null,"PLEASE SELECT A TEAM");
       
}
else 
{
    int res=JOptionPane.showConfirmDialog(null,"ARE YOU SURE YOU ENTERED THE CORRECT TEAMS?");
    if(res==JOptionPane.YES_OPTION)
    {
        bat1.setEnabled(true);
        bowl1.setEnabled(true);
        bat2.setEnabled(true);
        bowl2.setEnabled(true);
        inn11.setEnabled(true);
        inn12.setEnabled(true);
        inn21.setEnabled(true);
        inn22.setEnabled(true);
        t1.setEnabled(false);
        t2.setEnabled(false);
    }
   
   

}


// TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
String tn11=(String) t1.getSelectedItem();
String tn22=(String) t2.getSelectedItem();
if(tn11==tn22)
{
    JOptionPane.showMessageDialog(null,"PLEASE SELECT TWO DIFFERENT TEAMS");
       
}else if(tn11=="---select team---" || tn22=="---select team---")
{
    JOptionPane.showMessageDialog(null,"PLEASE SELECT A TEAM");
   
}
else         
{
    int res=JOptionPane.showConfirmDialog(null,"ARE YOU SURE YOU ENTERED THE CORRECT TEAMS?");
    if(res==JOptionPane.YES_OPTION)
    {
        bat1.setEnabled(true);
        bowl1.setEnabled(true);
        bat2.setEnabled(true);
        bowl2.setEnabled(true);
        inn11.setEnabled(true);
        inn12.setEnabled(true);
        inn21.setEnabled(true);
        inn22.setEnabled(true);
        t1.setEnabled(false);
        t2.setEnabled(false);
    }
    
  
}       // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusLost
// TODO add your handling code here:
    }//GEN-LAST:event_t1FocusLost

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t1FocusGained

    private void matchdaynoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchdaynoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matchdaynoActionPerformed

    private void bat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bat2ActionPerformed
if(bat2.isSelected()==true)
{
    bowl1.setSelected(true);
}
if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_bat2ActionPerformed

    private void st2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st2ActionPerformed

    private void bowl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowl1ActionPerformed
if(bowl1.isSelected()==true)
{
    bat2.setSelected(true);
    
}
if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}
// TODO add your handling code here:
    }//GEN-LAST:event_bowl1ActionPerformed

    private void inn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inn11ActionPerformed
if(inn11.isSelected()==true)
{
    inn21.setSelected(true);
    
}
if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_inn11ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
int r16=Integer.parseInt(st1.getText());
r16=r16+6;
st1.setText(""+r16);
// TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
int r14=Integer.parseInt(st1.getText());
r14=r14+4;
st1.setText(""+r14);        // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
int r13=Integer.parseInt(st1.getText());
r13=r13+3;
st1.setText(""+r13);        // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
int r12=Integer.parseInt(st1.getText());
r12=r12+2;
st1.setText(""+r12);        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
int r11=Integer.parseInt(st1.getText());
r11=r11+1;
st1.setText(""+r11);        // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
int r26=Integer.parseInt(st2.getText());
r26=r26+6;
st2.setText(""+r26);        // TODO add your handling code here:
    }//GEN-LAST:event_b26ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
int r24=Integer.parseInt(st2.getText());
r24=r24+4;
st2.setText(""+r24);        // TODO add your handling code here:
    }//GEN-LAST:event_b24ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
int r23=Integer.parseInt(st2.getText());
r23=r23+3;
st2.setText(""+r23);        // TODO add your handling code here:
    }//GEN-LAST:event_b23ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
int r22=Integer.parseInt(st2.getText());
r22=r22+2;
st2.setText(""+r22);        // TODO add your handling code here:
    }//GEN-LAST:event_b22ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
int r21=Integer.parseInt(st2.getText());
r21=r21+1;
st2.setText(""+r21);        // TODO add your handling code here:
    }//GEN-LAST:event_b21ActionPerformed

    private void w1plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w1plusActionPerformed
int w1p=Integer.parseInt(wicket1.getText());
w1p=w1p+1;
wicket1.setText(""+w1p);           // TODO add your handling code here:
    }//GEN-LAST:event_w1plusActionPerformed

    private void w1minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w1minusActionPerformed
int w1m=Integer.parseInt(wicket1.getText());
w1m=w1m-1;
wicket1.setText(""+w1m);         // TODO add your handling code here:
    }//GEN-LAST:event_w1minusActionPerformed

    private void w2plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w2plusActionPerformed
int w2p=Integer.parseInt(wicket2.getText());
w2p=w2p+1;
wicket2.setText(""+w2p);        // TODO add your handling code here:
    }//GEN-LAST:event_w2plusActionPerformed

    private void w2minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w2minusActionPerformed
int w2m=Integer.parseInt(wicket2.getText());
w2m=w2m-1;
wicket2.setText(""+w2m);         // TODO add your handling code here:
    }//GEN-LAST:event_w2minusActionPerformed

    private void bat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bat1ActionPerformed
if(bat1.isSelected()==true)
{
    bowl2.setSelected(true);
   
}
if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_bat1ActionPerformed

    private void bowl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowl2ActionPerformed
if(bowl2.isSelected()==true)
{
    bat1.setSelected(true);
}
if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_bowl2ActionPerformed

    private void inn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inn12ActionPerformed
if(inn12.isSelected()==true)
{
    inn22.setSelected(true);
    
} 
if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_inn12ActionPerformed

    private void inn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inn22ActionPerformed
        if(inn22.isSelected()==true)
        {
            inn12.setSelected(true);
        }  
        if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_inn22ActionPerformed

    private void inn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inn21ActionPerformed
        if(inn21.isSelected()==true)
        {
            inn11.setSelected(true);
        }   
        if((bat1.isSelected()==true || bowl1.isSelected()==true) && (inn11.isSelected()==true || inn22.isSelected()==true))
{
    cbutton.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_inn21ActionPerformed

    private void cbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbuttonActionPerformed
bat1.setEnabled(false);
bat2.setEnabled(false);
bowl1.setEnabled(false);
bowl2.setEnabled(false);
inn11.setEnabled(false);
inn12.setEnabled(false);
inn21.setEnabled(false);
inn22.setEnabled(false);
if(bat1.isSelected()==true && inn11.isSelected()==true)
{
    st1.setEnabled(true);
    wicket1.setEnabled(true);
    w1plus.setEnabled(true);
    w1minus.setEnabled(true);
    b16.setEnabled(true);
    b14.setEnabled(true);
    b13.setEnabled(true);
    b12.setEnabled(true);
    b11.setEnabled(true);
    cbutton.setEnabled(false);
    next.setEnabled(true);
    
 }
if(bowl1.isSelected()==true && inn11.isSelected()==true)
{
    st2.setEnabled(true);
    wicket2.setEnabled(true);
    w2plus.setEnabled(true);
    w2minus.setEnabled(true);
    b26.setEnabled(true);
    b24.setEnabled(true);
    b23.setEnabled(true);
    b22.setEnabled(true);
    b21.setEnabled(true);
    cbutton.setEnabled(false);
    next.setEnabled(true);
}
if(bat1.isSelected()==true && inn12.isSelected()==true)
{
    st2.setEnabled(true);
    wicket2.setEnabled(true);
    w2plus.setEnabled(true);
    w2minus.setEnabled(true);
     b26.setEnabled(true);
    b24.setEnabled(true);
    b23.setEnabled(true);
    b22.setEnabled(true);
    b21.setEnabled(true);
    cbutton.setEnabled(false);
    next.setEnabled(true);
}
if(bowl1.isSelected()==true && inn12.isSelected()==true)
{
    st1.setEnabled(true);
    wicket1.setEnabled(true);
    w1plus.setEnabled(true);
    w1minus.setEnabled(true);
     b16.setEnabled(true);
    b14.setEnabled(true);
    b13.setEnabled(true);
    b12.setEnabled(true);
    b11.setEnabled(true);
    cbutton.setEnabled(false);
    next.setEnabled(true);
}


    }//GEN-LAST:event_cbuttonActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
int run1=Integer.parseInt(st1.getText());
int run2=Integer.parseInt(st2.getText());
int wt1=Integer.parseInt(wicket1.getText());
int wt2=Integer.parseInt(wicket2.getText());
if((run1>0 && (wt1>=0 && wt1<=10)) &&(( bat1.isSelected()==true && inn11.isSelected()==true) || (bowl1.isSelected()==true && inn12.isSelected()==true)) )
{
    st2.setEnabled(true);
    wicket2.setEnabled(true);
    w2plus.setEnabled(true);
    w2minus.setEnabled(true);
     b26.setEnabled(true);
    b24.setEnabled(true);
    b23.setEnabled(true);
    b22.setEnabled(true);
    b21.setEnabled(true);
    st1.setEditable(false);
    wicket1.setEditable(false);
    w1plus.setEnabled(false);
    w1minus.setEnabled(false);
    b16.setEnabled(false);
    b14.setEnabled(false);
    b13.setEnabled(false);
    b12.setEnabled(false);
    b11.setEnabled(false);
    next.setEnabled(false);
    finish.setEnabled(true);
    inn22.setSelected(true);
    inn12.setSelected(true);
    inn22.setVisible(true);
    inn12.setVisible(true);
    inn11.setVisible(false);
    inn21.setVisible(false);
    bowl1.setSelected(true);
    bat2.setSelected(true);
}else if((run2>0 && (wt2>=0 && wt2<=10)) && ((bat1.isSelected()==true && inn12.isSelected()==true) || (bowl1.isSelected()==true && inn11.isSelected()==true)) )
{
     st1.setEnabled(true);
    wicket1.setEnabled(true);
    w1plus.setEnabled(true);
    w1minus.setEnabled(true);
     b16.setEnabled(true);
    b14.setEnabled(true);
    b13.setEnabled(true);
    b12.setEnabled(true);
    b11.setEnabled(true);
    st2.setEditable(false);
    wicket2.setEditable(false);
    w2plus.setEnabled(false);
    w2minus.setEnabled(false);
    b26.setEnabled(false);
    b24.setEnabled(false);
    b23.setEnabled(false);
    b22.setEnabled(false);
    b21.setEnabled(false);
    next.setEnabled(false);
    finish.setEnabled(true);
    inn22.setSelected(true);
    inn22.setVisible(true);
    inn12.setVisible(true);
    inn12.setSelected(true);
    inn11.setVisible(false);
    inn21.setVisible(false);
    bat1.setSelected(true);
    bowl2.setSelected(true);
}else
{
    JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SCORES CORRECTLY");
}// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scoreboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b16;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b26;
    private javax.swing.JRadioButton bat1;
    private javax.swing.JRadioButton bat2;
    private javax.swing.JRadioButton bowl1;
    private javax.swing.JRadioButton bowl2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton cbutton;
    private javax.swing.JButton finish;
    private javax.swing.JRadioButton inn11;
    private javax.swing.JRadioButton inn12;
    private javax.swing.JRadioButton inn21;
    private javax.swing.JRadioButton inn22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField matchdayno;
    private javax.swing.JButton next;
    private javax.swing.JTextField st1;
    private javax.swing.JTextField st2;
    private javax.swing.JComboBox<String> t1;
    private javax.swing.JComboBox<String> t2;
    private javax.swing.JButton w1minus;
    private javax.swing.JButton w1plus;
    private javax.swing.JButton w2minus;
    private javax.swing.JButton w2plus;
    private javax.swing.JTextField wicket1;
    private javax.swing.JTextField wicket2;
    // End of variables declaration//GEN-END:variables
}
