/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricketproj2021;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class teamdetails extends javax.swing.JFrame {

    /**
     * Creates new form teamdetails
     */
    public teamdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p8 = new javax.swing.JTextField();
        p7 = new javax.swing.JTextField();
        p11 = new javax.swing.JTextField();
        p9 = new javax.swing.JTextField();
        p10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        proceed = new javax.swing.JButton();
        rtest = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTER TEAM NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 194, 28));

        jPanel1.setBackground(new java.awt.Color(255, 227, 159));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PLAYER 1");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 45, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("ENTER THE PLAYER NAMES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("PLAYER 2");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 82, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("PLAYER 3");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 114, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PLAYER 4");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 146, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("PLAYER 5");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 178, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("PLAYER 6");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("PLAYER 7");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 242, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("PLAYER 8");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 274, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("PLAYER 9");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 311, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("PLAYER 10");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 343, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("PLAYER 11");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 375, -1, -1));
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 45, 220, -1));
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 82, 220, -1));
        jPanel1.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 216, 220, -1));
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 120, 220, -1));
        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 152, 220, -1));
        jPanel1.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 184, 220, -1));
        jPanel1.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 280, 220, -1));
        jPanel1.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 248, 220, -1));
        jPanel1.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 381, 220, -1));
        jPanel1.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 311, 220, -1));
        jPanel1.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 349, 220, -1));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 57, 520, 430));

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, -1));

        proceed.setText("PROCEED");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        getContentPane().add(proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        rtest.setEditable(false);
        getContentPane().add(rtest, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 42, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL TEAMS ENTERED");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cricketproj2021/teamdetails.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cricket","root","1192002");
            Statement stmt=con.createStatement();
            String str="Insert into teamdetails values('"+tname.getText()+"','"+p1.getText()+"','"+p2.getText()+"','"+p3.getText()+"','"+p4.getText()+"','"+p5.getText()+"','"+p6.getText()+"','"+p7.getText()+"','"+p8.getText()+"','"+p9.getText()+"','"+p10.getText()+"','"+p11.getText()+"');";
        stmt.executeUpdate(str);
        JOptionPane.showMessageDialog(null, "data saved");
        tname.setText(" ");
        p1.setText(" ");
        p2.setText(" ");
        p3.setText(" ");
        p4.setText(" ");
        p5.setText(" ");
        p6.setText(" ");
        p7.setText(" ");
        p8.setText(" ");
        p9.setText(" ");
        p10.setText(" ");
        p11.setText(" ");
        String s1="Select count(*) from teamdetails";
          ResultSet rs1=stmt.executeQuery(s1);
          if(rs1.next())
          {
               int R=rs1.getInt("count(*)");
               rtest.setText(""+R);
               if(R==5)
               {
                   proceed.setEnabled(true);
                   save.setEnabled(false);
                   p1.setEnabled(false);
                   p2.setEnabled(false);
                   p3.setEnabled(false);
                   p4.setEnabled(false);
                   p5.setEnabled(false);
                   p6.setEnabled(false);
                   p7.setEnabled(false);
                   p8.setEnabled(false);
                   p9.setEnabled(false);
                   p10.setEnabled(false);
                   p11.setEnabled(false);
                   tname.setEnabled(false);
                   JOptionPane.showMessageDialog(null,"Maximum limit of teams reached.Please proceed to main menu");
                   
                   
               }
          }
        
}catch(Exception e)
{
        JOptionPane.showMessageDialog(null, e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      JOptionPane.showMessageDialog(null, "ENTER TEAM DETAILS (EXACTLY 5)");
      proceed.setEnabled(false);
      try{
          Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cricket","root","1192002");
            Statement stmt=con.createStatement();
            String s1="Select count(*) from teamdetails";
          ResultSet rs1=stmt.executeQuery(s1);
          if(rs1.next())
          {
               int R=rs1.getInt("count(*)");
               rtest.setText(""+R);
               if(R==5)
               {
                   proceed.setEnabled(true);
                   save.setEnabled(false);
                   p1.setEnabled(false);
                   p2.setEnabled(false);
                   p3.setEnabled(false);
                   p4.setEnabled(false);
                   p5.setEnabled(false);
                   p6.setEnabled(false);
                   p7.setEnabled(false);
                   p8.setEnabled(false);
                   p9.setEnabled(false);
                   p10.setEnabled(false);
                   p11.setEnabled(false);
                   tname.setEnabled(false);
                   JOptionPane.showMessageDialog(null,"Maximum limit of teams reached.Please proceed to main menu");
                   
                   
               }
          }
          
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
      }
      
    }//GEN-LAST:event_formWindowOpened

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
    mainframe mf =new mainframe();
    mf.setVisible(true);    
    this.dispose();        // TODO add your handling code here:
      
    }//GEN-LAST:event_proceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teamdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teamdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teamdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teamdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teamdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p10;
    private javax.swing.JTextField p11;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextField p8;
    private javax.swing.JTextField p9;
    private javax.swing.JButton proceed;
    private javax.swing.JTextField rtest;
    private javax.swing.JButton save;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
}
